// <auto-generated />
using System;
using BlogZ.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240725120206_updateAuthor")]
    partial class updateAuthor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Biography")
                        .HasColumnType("text")
                        .HasColumnName("Biography");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("ProfileImageURL")
                        .HasColumnType("text")
                        .HasColumnName("ProfilePictureImageURL");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedDate");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1429bdd8-ad1e-4253-86ee-e5d015782465"),
                            Biography = "This is John Doe's biography.",
                            BlogId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProfileImageURL = "https://example.com/profilepicture.jpg",
                            UserId = "71d486c1-f9a5-43f6-b329-1a8e386b773b"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("AuthorId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedDate");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.ToTable("Blogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("48d2c3d1-6b6a-44d5-a411-fa14c9ecc8e4"),
                            AuthorId = new Guid("1429bdd8-ad1e-4253-86ee-e5d015782465"),
                            CreatedDate = new DateTime(2024, 7, 25, 12, 2, 5, 49, DateTimeKind.Utc).AddTicks(6390)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("AuthorId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedDate");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("PostId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AuthorId" }, "Comment_AuthorId_Index");

                    b.HasIndex(new[] { "PostId" }, "Comment_PostId_Index");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uuid")
                        .HasColumnName("BlogId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageURL")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CoverImageURL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedDate");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("IsPublic");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("efae1367-0049-442f-9601-a2663e3e99f0"),
                            BlogId = new Guid("48d2c3d1-6b6a-44d5-a411-fa14c9ecc8e4"),
                            Content = "This post covers the basics of programming...",
                            CoverImageURL = "https://example.com/cover1.jpg",
                            CreatedDate = new DateTime(2024, 7, 25, 12, 2, 5, 49, DateTimeKind.Utc).AddTicks(6423),
                            IsPublic = true,
                            Slug = "introduction-to-programming",
                            Title = "Introduction to Programming"
                        },
                        new
                        {
                            Id = new Guid("85c98ba7-e760-424f-b46c-dec33662fa67"),
                            BlogId = new Guid("48d2c3d1-6b6a-44d5-a411-fa14c9ecc8e4"),
                            Content = "This post delves into advanced concepts in software engineering...",
                            CoverImageURL = "https://example.com/cover2.jpg",
                            CreatedDate = new DateTime(2024, 7, 25, 12, 2, 5, 49, DateTimeKind.Utc).AddTicks(6426),
                            IsPublic = true,
                            Slug = "advanced-software-engineering",
                            Title = "Advanced Software Engineering"
                        },
                        new
                        {
                            Id = new Guid("a5d1792a-5b00-48fd-a9b3-5c20a10440e8"),
                            BlogId = new Guid("48d2c3d1-6b6a-44d5-a411-fa14c9ecc8e4"),
                            Content = "Exploring the fascinating world of science...",
                            CoverImageURL = "https://example.com/cover3.jpg",
                            CreatedDate = new DateTime(2024, 7, 25, 12, 2, 5, 49, DateTimeKind.Utc).AddTicks(6428),
                            IsPublic = true,
                            Slug = "th-Wonders-of-science",
                            Title = "The Wonders of Science"
                        },
                        new
                        {
                            Id = new Guid("59944914-30f8-48cb-96df-0c4d951ba429"),
                            BlogId = new Guid("48d2c3d1-6b6a-44d5-a411-fa14c9ecc8e4"),
                            Content = "A comprehensive guide to building web applications with ASP.NET Core MVC...",
                            CoverImageURL = "https://example.com/cover4.jpg",
                            CreatedDate = new DateTime(2024, 7, 25, 12, 2, 5, 49, DateTimeKind.Utc).AddTicks(6430),
                            IsPublic = true,
                            Slug = "asp.net-core-mvc-tutorial",
                            Title = "ASP.NET Core MVC Tutorial"
                        },
                        new
                        {
                            Id = new Guid("878da7c3-014a-4bc6-910b-67dc46ab1f36"),
                            BlogId = new Guid("48d2c3d1-6b6a-44d5-a411-fa14c9ecc8e4"),
                            Content = "Discussing the best practices every programmer should follow...",
                            CoverImageURL = "https://example.com/cover5.jpg",
                            CreatedDate = new DateTime(2024, 7, 25, 12, 2, 5, 49, DateTimeKind.Utc).AddTicks(6432),
                            IsPublic = true,
                            Slug = "best-ractices-in-rogramming",
                            Title = "Best Practices in Programming"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NormalizedName");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex(new[] { "NormalizedName" }, "Tag_NormalizedName_UK")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("72f8d61f-83d0-4e15-9ae1-dff92de65b3b"),
                            CreatedDate = new DateTime(2024, 7, 25, 12, 2, 5, 49, DateTimeKind.Utc).AddTicks(6396),
                            Description = "All things programming",
                            Name = "#Programming",
                            NormalizedName = "#PROGRAMMING"
                        },
                        new
                        {
                            Id = new Guid("c35ccca6-f53a-4818-9c47-8af09dbdd1a6"),
                            CreatedDate = new DateTime(2024, 7, 25, 12, 2, 5, 49, DateTimeKind.Utc).AddTicks(6413),
                            Description = "Software engineering topics",
                            Name = "#SoftwareEngineering",
                            NormalizedName = "#SOFTWAREENGINEERING"
                        },
                        new
                        {
                            Id = new Guid("568601ad-9bdd-4fdb-94de-c05ee1d85e20"),
                            CreatedDate = new DateTime(2024, 7, 25, 12, 2, 5, 49, DateTimeKind.Utc).AddTicks(6415),
                            Description = "Scientific discoveries and discussions",
                            Name = "#Science",
                            NormalizedName = "#SCIENCE"
                        },
                        new
                        {
                            Id = new Guid("76ada677-eaf5-4d7f-af6e-b87db0c8ba8e"),
                            CreatedDate = new DateTime(2024, 7, 25, 12, 2, 5, 49, DateTimeKind.Utc).AddTicks(6418),
                            Description = "ASP.NET related content",
                            Name = "#ASP.Net",
                            NormalizedName = "#ASP.NET"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "bcbd0ce6-22aa-4640-ad03-e274a3e707fa",
                            ConcurrencyStamp = "bcbd0ce6-22aa-4640-ad03-e274a3e707fa",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "f69382d4-bbb9-455c-8d44-c934e4797f6c",
                            ConcurrencyStamp = "f69382d4-bbb9-455c-8d44-c934e4797f6c",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "4c793ddb-0952-4d75-aaec-641ef2b3b946",
                            ConcurrencyStamp = "4c793ddb-0952-4d75-aaec-641ef2b3b946",
                            Name = "Author",
                            NormalizedName = "AUTHOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "71d486c1-f9a5-43f6-b329-1a8e386b773b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1485c4fe-773d-4742-a179-e45a9f32a92c",
                            Email = "johndoe@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHNDOE@EMAIL.COM",
                            NormalizedUserName = "JOHNDOE",
                            PasswordHash = "AQAAAAIAAYagAAAAEHKZrz9f7cdB+uE6gYyEXN2teUA9aBYG5EpNjbO4KatfhqVbwGJQPTI/WaH+IoqKEw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "johndoe"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "71d486c1-f9a5-43f6-b329-1a8e386b773b",
                            RoleId = "bcbd0ce6-22aa-4640-ad03-e274a3e707fa"
                        },
                        new
                        {
                            UserId = "71d486c1-f9a5-43f6-b329-1a8e386b773b",
                            RoleId = "f69382d4-bbb9-455c-8d44-c934e4797f6c"
                        },
                        new
                        {
                            UserId = "71d486c1-f9a5-43f6-b329-1a8e386b773b",
                            RoleId = "4c793ddb-0952-4d75-aaec-641ef2b3b946"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Domain.Entities.Author", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Blog", b =>
                {
                    b.HasOne("Domain.Entities.Author", "Author")
                        .WithOne("Blog")
                        .HasForeignKey("Domain.Entities.Blog", "AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Domain.Entities.Comment", b =>
                {
                    b.HasOne("Domain.Entities.Author", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.HasOne("Domain.Entities.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.HasOne("Domain.Entities.Post", null)
                        .WithMany("Tags")
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("Domain.Entities.Author", b =>
                {
                    b.Navigation("Blog")
                        .IsRequired();

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Domain.Entities.Blog", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
